### ISSUE TITLE
No TOKEN!!!

### ISSUE THREAD

**Issue by yusung103** [Team-Wander/Wandering-Server#101]
### Summary

health check 확인 할 때 토큰 없이 접근할 수 있도록 구현

**Comment by jjyutm4532** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified SecurityConfig.java to permit all requests to the Actuator health endpoint without authentication. This change ensures that the health check can be performed without requiring a token.

You can review changes in this commit: https://github.com/jjyutm4532/Team-Wander-Wandering-Server-101/commit/cb7301e48b742aa6a13c95eb303ed6c0227d5c51.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
